import { Mic, BarChart3, Target, LineChart } from "lucide-react";
import FeatureCard from "./FeatureCard/FeatureCard";
import VisualHeader from "../../VisualHeader/VisualHeader";

const features = [
  {
    title: "AI Mock Interviews",
    desc: "Engage in lifelike simulations with adaptive questions generated by our core AI engine.",
    icon: <Mic size={32} />,
  },
  {
    title: "Structured Feedback",
    desc: "Receive comprehensive reports on your tone, technical accuracy, and body language.",
    icon: <BarChart3 size={32} />,
  },
  {
    title: "Skill Gap Analysis",
    desc: "Identify the exact missing pieces in your knowledge compared to industry benchmarks.",
    icon: <Target size={32} />,
  },
  {
    title: "Progress Tracking",
    desc: "Visualize your growth over time with interactive charts and historical performance data.",
    icon: <LineChart size={32} />,
  }
];

const Features = () => {
  return (
    <section className="min-h-[calc(100vh-70px)] flex items-center py-12 md:py-8 relative overflow-hidden">
      <div className="mx-auto w-full max-w-7xl px-4 relative z-1">
        <div className="mb-6 text-center">
          <VisualHeader
            badge="Core Capabilities"
            title="Everything you need to"
            gradient_title="succeed."
            subtitle="HirePilot combines advanced AI with proven coaching methods to turn your weaknesses into your greatest strengths."
          />
        </div>

        <div className="grid grid-cols-12 gap-6">
          {features.map((feature, index) => (
            <div className="col-span-12 md:col-span-6 lg:col-span-3" key={index}>
              <FeatureCard {...feature} />
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;
